language: node_js
cache: yarn
node_js:
  - stable
  - "10"
  - "8"
  - "6"

install:
  - npm install -g codecov

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
